import argparse
import os
from datetime import datetime

from app.ai_engine import AIEngine
from app.tts_engine import SpeechSynthesizer
from app.agent import LocalGuideAgent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Local Guide Speech Agent (Hugging Face Inference API)")
    parser.add_argument("--query", required=True, help="User query to guide the recommendation")
    parser.add_argument(
        "--ai-json",
        default="/workspace/data/ai_engine_sample.json",
        help="Path to a JSON file containing AI_engine output with a 'text' field",
    )
    parser.add_argument(
        "--out",
        default="/workspace/output/recommendation.wav",
        help="Output WAV file path for synthesized speech (generated by HF Inference API)",
    )
    parser.add_argument(
        "--hf-model",
        default="espnet/kan-bayashi-ljspeech-vits",
        help="Hugging Face TTS model id to use via Inference API",
    )
    parser.add_argument(
        "--hf-token",
        default=None,
        help="Hugging Face API token (falls back to env HUGGINGFACE_API_TOKEN or HF_TOKEN)",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=60.0,
        help="HTTP request timeout to the HF Inference API (seconds)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    out_path = args.out
    if out_path == "/workspace/output/recommendation.wav" and os.path.exists(out_path):
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = f"/workspace/output/recommendation_{ts}.wav"

    ai_engine = AIEngine(source_json_path=args.ai_json)
    tts = SpeechSynthesizer(
        model_id=args.hf_model,
        api_token=args.hf_token or os.getenv("HUGGINGFACE_API_TOKEN") or os.getenv("HF_TOKEN"),
        timeout_seconds=args.timeout,
    )
    agent = LocalGuideAgent(ai_engine=ai_engine, speech_synthesizer=tts)

    result = agent.handle_query(args.query, out_path)

    print("Recommendation:\n")
    print(result["recommendation_text"])

    print("\nAudio saved to:", result["audio_path"])


if __name__ == "__main__":
    main()